[workspace]
resolver = "2"
members = [
    "webtrans",
    "webtrans-proto", 
    "webtrans-quinn", 
    "webtrans-trait", 
    "webtrans-wasm", 
    "webtrans-wasm-demo"
]

[workspace.package]
version = "0.4.0"
edition = "2024"
authors = ["shellrow <shellrow@foctal.com>"]
rust-version = "1.85"

[workspace.dependencies]
webtrans-proto = { path = "webtrans-proto", version = "0.4.0" }
webtrans-trait = { path = "webtrans-trait", version = "0.4.0" }
webtrans-quinn = { path = "webtrans-quinn", version = "0.4.0" }
webtrans-wasm = { path = "webtrans-wasm", version = "0.4.0" }
bytes = "1"
thiserror = "2"
http = "1"
url = "2"
tracing = "0.1"
