[package]
name = "webtrans-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
futures = "0.3"
webtrans-proto = { path = "../webtrans-proto", features = ["fuzzing"] }

[workspace]
members = ["."]

[[bin]]
name = "varint"
path = "fuzz_targets/varint.rs"
test = false
doc = false
bench = false

[[bin]]
name = "qpack_huffman"
path = "fuzz_targets/qpack_huffman.rs"
test = false
doc = false
bench = false

[[bin]]
name = "frame"
path = "fuzz_targets/frame.rs"
test = false
doc = false
bench = false

[[bin]]
name = "settings"
path = "fuzz_targets/settings.rs"
test = false
doc = false
bench = false

[[bin]]
name = "connect"
path = "fuzz_targets/connect.rs"
test = false
doc = false
bench = false

[[bin]]
name = "capsule"
path = "fuzz_targets/capsule.rs"
test = false
doc = false
bench = false
